townteki/townsquare-client

- pages/Decks.jsx
- pages/Register.jsx
Remove using of env variable in the browser code, not working
> Update test code

- Components/Form/formFields.json
- pages/ForgotPassword.jsx
- pages/Profile.jsx
> Password handling

- less/cards.less
- less/site.less
- less/variables.less
- updated color for the links
- adjusted card sized to deal with the "shadow" on the focused card
- adjusted position/offset on the booted cards (standard size).
> Minor UI changes links, boot cards, focus

- Components/GameBoard/Card.jsx
- Components/GameBoard/DrawDeck.jsx
- Components/GameBoard/DrawHandPanel.jsx
- Components/GameBoard/GameBoard.jsx
- Components/GameBoard/PlayerRow.jsx
- Components/GameBoard/SquishableCardPanel.jsx
- Components/Games/Game.js
- Components/Games/GamePlayer.js
- less/common.less
- less/gameboard.less
- less/gamelist.less
- less/variables.less
Improves parts mentioned in issue #18
> Draw hand UI update

- Components/GameBoard/Card.jsx
- Components/GameBoard/DrawDeck.jsx
- Components/GameBoard/GameBoard.jsx
- Components/GameBoard/PlayerRow.jsx
- less/cards.less
- less/gameboard.less
- less/location.less
Center the town, remove unnecessary menu item for draw deck and add auto-alignment for multiple attachments.
> UI improvements

- Components/GameBoard/Card.jsx
- Components/GameBoard/Droppable.jsx
- less/cards.less
- drag rules for being played pile
- booted attachment hover
> Some updates and fixes

- Components/GameBoard/Card.jsx
- Components/GameBoard/PlayerStats.jsx
> Fix some UI bugs

- Components/GameBoard/Card.jsx
Do not propagate click on the attachment list panel.
> Attachment handling

- pages/HowToPlay.jsx
Still need to update the Action Windows section to be Doomtown specific
> updated How To Play with Doomtown references

- Components/GameBoard/GameBoard.jsx
- Components/GameBoard/StatusPanel.jsx
Present shootout info in the shootout panel. So far without any nice formatting, and without effects. That will be done later.
#48
> Show Shootout Info

- Components/Decks/DeckEditor.jsx
- Components/Decks/RestrictedListDropdown.jsx
- reducers/cards.js
Fixes problem with `108 Gracious Gifts` not appearing in outfit drop down list.
> Parse outfit with pack code

- Components/GameBoard/DrawHandPanel.jsx
- Components/GameBoard/GameBoard.jsx
- Components/GameBoard/PlayerRow.jsx
- Components/GameBoard/PopupDefaults.js
- Components/GameBoard/SquishableCardPanel.jsx
- less/gameboard.less
- do not close popup after hand redraw
- fix default position of the being played and draw hand popups
> Draw hand popup updates

- Components/GameBoard/ActivePlayerPrompt.jsx
- Components/GameBoard/GameBoard.jsx
- Components/GameBoard/Messages.jsx
- Components/GameBoard/MessagesTokens.js
- less/gameboard.less
Backend part: townteki/townsquare#1192
> Create Info area in player prompt

- Components/Decks/DeckRow.jsx
> adjust number of columns if given deck has legend.

- Components/GameBoard/GameBoard.jsx
- Components/GameBoard/StatusPanel.jsx
- Components/GameBoard/TimeLimitClock.jsx
- less/status.less
backend part: townteki/townsquare#1379
> Add time panel

- less/chat.less
- less/site.less
- package-lock.json
- package.json
- pages/Lobby.jsx
backend part: townteki/townsquare#1491
> Add Discord chat widget

- Components/GameBoard/DrawHandPanel.jsx
- Components/GameBoard/GameBoard.jsx
backend part townteki/townsquare#1504
> Add Keep Selected button to draw hand

- Components/GameBoard/ActivePlayerPrompt.jsx
- Components/GameBoard/CardPrompt.jsx
- Components/Games/PendingGame.jsx
- less/gameboard.less
backend part: townteki/townsquare#1520
> Take Yer Lumps step improvement

- Components/GameBoard/Card.jsx
- less/cards.less
Backend part: townteki/townsquare#1538
> Update marked card statusClass

- Components/GameBoard/GameBoard.jsx
- Components/GameBoard/GameLocation.jsx
- Components/GameBoard/PlayerStreet.jsx
- pages/Profile.jsx
Add option to profile to turn off background textures for locations, and sidewalks with move arrows.
> Add option to turn of bg texture
